puts '- Brand'

taxonomy = Spree::Taxonomy.find_by_name!('Brand')
# taxon = Spree::Taxon.find_by_name!('Brand')
taxon = Spree::Taxon.joins(:translations).where(spree_taxon_translations: {name: 'Brand'}).first

Spree::Taxon.create!(name: 'Ray-Ban', taxonomy: taxonomy, parent: taxon, position: 1)
Spree::Taxon.create!(name: 'Ray-Ban Junior', taxonomy: taxonomy, parent: taxon, position: 2)
Spree::Taxon.create!(name: 'Nueu', taxonomy: taxonomy, parent: taxon, position: 3)
Spree::Taxon.create!(name: 'Oakley', taxonomy: taxonomy, parent: taxon, position: 4)
Spree::Taxon.create!(name: 'Carrera', taxonomy: taxonomy, parent: taxon, position: 5)
Spree::Taxon.create!(name: 'Maui Jim', taxonomy: taxonomy, parent: taxon, position: 6)
Spree::Taxon.create!(name: 'Bloc', taxonomy: taxonomy, parent: taxon, position: 7)
Spree::Taxon.create!(name: 'Dior', taxonomy: taxonomy, parent: taxon, position: 8)
Spree::Taxon.create!(name: 'Persol', taxonomy: taxonomy, parent: taxon, position: 9)
Spree::Taxon.create!(name: 'Prada', taxonomy: taxonomy, parent: taxon, position: 10)
Spree::Taxon.create!(name: 'Tom Ford', taxonomy: taxonomy, parent: taxon, position: 11)
Spree::Taxon.create!(name: 'Dolce & Gabbana', taxonomy: taxonomy, parent: taxon, position: 12)
Spree::Taxon.create!(name: 'Revo', taxonomy: taxonomy, parent: taxon, position: 13)
Spree::Taxon.create!(name: 'Gucci', taxonomy: taxonomy, parent: taxon, position: 14)
Spree::Taxon.create!(name: 'Costa', taxonomy: taxonomy, parent: taxon, position: 15)

Spree::Taxon.create!(name: 'Acuvue', taxonomy: taxonomy, parent: taxon, position: 16)
Spree::Taxon.create!(name: 'Air Optics', taxonomy: taxonomy, parent: taxon, position: 17)
Spree::Taxon.create!(name: 'Bausch & Lomb', taxonomy: taxonomy, parent: taxon, position: 18)
Spree::Taxon.create!(name: 'Biofinity', taxonomy: taxonomy, parent: taxon, position: 19)
Spree::Taxon.create!(name: 'Boston', taxonomy: taxonomy, parent: taxon, position: 20)
Spree::Taxon.create!(name: 'Ciba Vision', taxonomy: taxonomy, parent: taxon, position: 20)
Spree::Taxon.create!(name: 'Dailies', taxonomy: taxonomy, parent: taxon, position: 21)
Spree::Taxon.create!(name: 'Focus', taxonomy: taxonomy, parent: taxon, position: 22)
Spree::Taxon.create!(name: 'Frequency', taxonomy: taxonomy, parent: taxon, position: 23)
Spree::Taxon.create!(name: 'Freshlook', taxonomy: taxonomy, parent: taxon, position: 24)
Spree::Taxon.create!(name: 'Proclear', taxonomy: taxonomy, parent: taxon, position: 25)
Spree::Taxon.create!(name: 'Pure Vision', taxonomy: taxonomy, parent: taxon, position: 26)
Spree::Taxon.create!(name: 'Softlens', taxonomy: taxonomy, parent: taxon, position: 27)
